# Generated by Django 3.0.5 on 2020-05-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobyescoth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.TextField()),
                ('created_date', models.DateField()),
            ],
            options={
                'db_table': 'jobyes',
            },
        ),
    ]
