export const FETCH_POSITION_REQUEST = 'FETCH_POSITION_REQUEST'
export const FETCH_POSITION_SUCCESS = 'FETCH_POSITION_SUCCESS'
export const FETCH_POSITION_FAILURE = 'FETCH_POSITION_FAILURE'
export const DELETE_POSITION_SUCCESS = 'DELETE_POSITION_SUCCESS'