export const FETCH_THJOBSJOBYES_REQUEST = 'FETCH_THJOBSJOBYES_REQUEST'
export const FETCH_THJOBSJOBYES_SUCCESS = 'FETCH_THJOBSJOBYES_SUCCESS'
export const FETCH_THJOBSJOBYES_FAILURE = 'FETCH_THJOBSJOBYES_FAILURE'