export const FETCH_THJOBSTHAI_REQUEST = 'FETCH_THJOBSTHAI_REQUEST'
export const FETCH_THJOBSTHAI_SUCCESS = 'FETCH_THJOBSTHAI_SUCCESS'
export const FETCH_THJOBSTHAI_FAILURE = 'FETCH_THJOBSTHAI_FAILURE'