# Generated by Django 3.0.8 on 2020-07-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
            ],
            options={
                'db_table': 'jobs_db',
            },
        ),
    ]
