export const RESET_PASSWORD_CONFIRM_REQUEST = 'RESET_PASSWORD_CONFIRM_REQUEST'
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS'
export const RESET_PASSWORD_CONFIRM_FAILURE = 'RESET_PASSWORD_CONFIRM_FAILURE'