export const FETCH_THJOBSJOBTHAIWEB_REQUEST = 'FETCH_THJOBSJOBTHAIWEB_REQUEST'
export const FETCH_THJOBSJOBTHAIWEB_SUCCESS = 'FETCH_THJOBSJOBTHAIWEB_SUCCESS'
export const FETCH_THJOBSJOBTHAIWEB_FAILURE = 'FETCH_THJOBSJOBTHAIWEB_FAILURE'