export const FETCH_THJOBSTOPGUN_REQUEST = 'FETCH_THJOBSTOPGUN_REQUEST'
export const FETCH_THJOBSTOPGUN_SUCCESS = 'FETCH_THJOBSTOPGUN_SUCCESS'
export const FETCH_THJOBSTOPGUN_FAILURE = 'FETCH_THJOBSTOPGUN_FAILURE'