export const FETCH_THJOBSTHAIJOBCOM_REQUEST = 'FETCH_THJOBSTHAIJOBCOM_REQUEST'
export const FETCH_THJOBSTHAIJOBCOM_SUCCESS = 'FETCH_THJOBSTHAIJOBCOM_SUCCESS'
export const FETCH_THJOBSTHAIJOBCOM_FAILURE = 'FETCH_THJOBSTHAIJOBCOM_FAILURE'