export const FETCH_THJOBSMONSTER_REQUEST = 'FETCH_THJOBSMONSTER_REQUEST'
export const FETCH_THJOBSMONSTER_SUCCESS = 'FETCH_THJOBSMONSTER_SUCCESS'
export const FETCH_THJOBSMONSTER_FAILURE = 'FETCH_THJOBSMONSTER_FAILURE'

